[project]
name = "CircularStereoAlgorithm_SI"
version = "1.0.0"
description = "Supporting Information"
readme = "README.md"
requires-python = "==3.14"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "rdkit==2024.09.6",
    "scipy>=1.16.1",
    "stereomolgraph==0.0.21b0",
    "tqdm>=4.50",
]